#######################
## Availabilty Zones ##
#######################

azs:
- name: z1

##############
## VM Types ##
##############

vm_types:
- name: default
  cloud_properties:
    ephemeral_disk:
      size: 1024
      type: gp2

################
## Disk Types ##
################

disk_types:
- name: default
  disk_size: 1024

#################
## Compilation ##
#################

compilation:
  workers: 2
  network: default
  az: z1
  reuse_compilation_vms: false
  vm_type: default

##############
## Networks ##
##############

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.4.0/24
    reserved: 10.244.4.1
    static: [10.244.4.2, 10.244.4.3]
    az: z1
    cloud_properties:
      name: random
